// <auto-generated />
namespace WebApplication5.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class posts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(posts));
        
        string IMigrationMetadata.Id
        {
            get { return "202105240303272_posts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
